default:
	

deckjs.css:
	rm -f deckjs.css
	cp ../deck.js/core/deck.core.css deckjs.css
	cat ../deck.js/extensions/goto/deck.goto.css >>deckjs.css
	cat ../deck.js/extensions/menu/deck.menu.css >>deckjs.css
	cat ../deck.js/extensions/navigation/deck.navigation.css >>deckjs.css
	cat ../deck.js/extensions/status/deck.status.css >>deckjs.css
	cat ../deck.js/extensions/hash/deck.hash.css >>deckjs.css
